modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "eeeabsmobs"
version = "0.4"
displayName = "EEEAB's Mobs"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/eeeabs-mobs"
logoFile = "banner.png"
authors = "EEEAB"
description = '''EEEAB's Mobs adds a variety of challenging mobs to your Minecraft world!'''
[[dependencies.eeeabsmobs]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.eeeabsmobs]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.eeeabsmobs]] #optional
# the modid of the dependency
modId = "citadel" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory = true #mandatory
# The version range of the dependency
versionRange = "[2.0.0,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering = "AFTER"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side = "BOTH"